# running mode (offline for stage 1-2, online for stage 3)
mode: offline

# dataset, checkpoints and logs
data_dir: ./dataset/Data_BloodMNIST/
client_ckp_dir: ./checkpoints/client/
global_ckp_dir: ./checkpoints/global/
log_dir: ./logs/

# update all client each iter or partially.
update_mode: all

device: cuda

# model (MLP/LeNet)
model: LeNet

# client params
n_clients: 20
n_update_clients: 20  # M

# training params
input_size: 28
output_channel: 8
batch_size: 32
n_rounds: 50
n_epochs: 50
lr: 0.0003
